"""empty message

Revision ID: 23a00f275c03
Revises: 
Create Date: 2024-05-10 01:50:25.650392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23a00f275c03'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_movie', sa.Boolean(), nullable=False))

    with op.batch_alter_table('recently__watched', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_movie', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recently__watched', schema=None) as batch_op:
        batch_op.drop_column('is_movie')

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_column('is_movie')

    # ### end Alembic commands ###
