"""empty message

Revision ID: 96631b4f5b4a
Revises: 
Create Date: 2024-05-16 00:14:37.649906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96631b4f5b4a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('film_image', sa.String(length=200), nullable=True))

    with op.batch_alter_table('recently__watched', schema=None) as batch_op:
        batch_op.add_column(sa.Column('film_image', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recently__watched', schema=None) as batch_op:
        batch_op.drop_column('film_image')

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_column('film_image')

    # ### end Alembic commands ###
